Cinema.WebUI/Models/ErrorViewModel.cs
using System;

namespace Cinema.WebUI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Cinema.WebUI/Models/FilmControlModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cinema.WebUI.Models
{
    public class FilmControlModel
    {
        public Guid Id { get; set; }

        public bool HasAccess { get; set; }
    }
}

Cinema.WebUI/Models/FilmFileModel.cs
using Cinema.Domain;
using Microsoft.AspNetCore.Http;

namespace Cinema.WebUI.Models
{
    public class FilmFileModel : FilmModel
    {
        public IFormFile FormFile { get; set; }
    }
}

Cinema.WebUI/Components/FilmControlViewComponent.cs
using System.Threading.Tasks;
using Cinema.Domain;
using Cinema.Domain.Identity;
using Cinema.Service;
using Cinema.WebUI.Models;
using Microsoft.AspNetCore.Mvc;

namespace Cinema.WebUI.Components
{
    public class FilmControlViewComponent : ViewComponent
    {
        private readonly ISecurityService _securityService;

        public FilmControlViewComponent(ISecurityService securityService)
        {
            _securityService = securityService;
        }

        public async Task<IViewComponentResult> InvokeAsync(FilmModel filmModel)
        {
            UserModel user = await _securityService.GetCurrentUser();
            FilmControlModel model = new FilmControlModel()
            {
                Id = filmModel.Id,
                HasAccess = user?.Id == filmModel.UserId

            };
            return View(model);
        }
    }
}

Cinema.WebUI/Controllers/FilmController.cs
using System;
using System.Diagnostics;
using System.IO;
using System.Threading.Tasks;
using Cinema.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Cinema.WebUI.Models;

namespace Cinema.WebUI.Controllers
{
    public class FilmController : Controller
    {
        private readonly ILogger<FilmController> _logger;
        private readonly IFilmService _filmService;

        public FilmController(ILogger<FilmController> logger,
            IFilmService filmService)
        {
            _logger = logger;
            _filmService = filmService;
        }

        public async Task<IActionResult> Page(int pageNumber = 1)
        {
            return View(await _filmService.GetFilms(pageNumber));
        }

        [HttpGet]
        public IActionResult NewFilm()
        {
            return View("AddEdit", new FilmFileModel());
        }

        [HttpPost]
        public async Task<IActionResult> NewFilm(FilmFileModel filmModel)
        {
            try
            {
                await SetImage(filmModel);
                await _filmService.CreateFilm(filmModel);

                return RedirectToAction("Page");
            }
            catch (Exception e)
            {
                ViewBag.MessageError = e.Message;
                return View("AddEdit", filmModel);
            }
        }

        [HttpGet("[controller]/[action]/{id}")]
        public async Task<IActionResult> Remove(string id)
        {
            try
            {
                await _filmService.RemoveFilm(Guid.Parse(id));
            }
            catch (Exception e)
            {
                ViewBag.MessageError = e.Message;
            }

            return RedirectToAction("Page");
        }

        [HttpGet("[controller]/[action]/{id}")]
        public async Task<IActionResult> EditFilm(string id)
        {
            var model = await _filmService.GetFilm(Guid.Parse(id));

            return View("AddEdit", new FilmFileModel()
            {
                Id = model.Id,
                Description = model.Description,
                ReleaseYear = model.ReleaseYear,
                User = model.User,
                Title = model.Title,
                Producer = model.Producer,
                Poster = "\\Images\\Movies\\" +model.Poster,
                UserId = model.UserId,
            });
        }

        [HttpPost]
        public async Task<IActionResult> EditFilm(FilmFileModel filmModel)
        {
            try
            {
                await SetImage(filmModel);
                await _filmService.UpdateFilm(filmModel);

                return RedirectToAction("Page");
            }
            catch (Exception e)
            {
                ViewBag.MessageError = e.Message;

                return View("AddEdit", filmModel);
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        private async Task SetImage(FilmFileModel filmModel)
        {
            if (filmModel.FormFile == null)
                return;

            await using MemoryStream stream = new MemoryStream();

            await filmModel.FormFile.CopyToAsync(stream);
            filmModel.File = stream.ToArray();
            filmModel.Poster = filmModel.FormFile.FileName;
        }
    }
}

Cinema.WebUI/Views/Film/AddEdit.cshtml
@model FilmFileModel
@if (!string.IsNullOrEmpty(@ViewBag.MessageError))
{
    <p class="error-message">@ViewBag.MessageError</p>
}
    <form asp-controller="Film" asp-action="@(Model.Id == Guid.Empty ? "NewFilm" : "EditFilm")" method="post" enctype="multipart/form-data">
        <input asp-for="UserId" type="hidden" />
        <input asp-for="Id" type="hidden" />
        <input asp-for="Poster" type="hidden" />
        @if (!string.IsNullOrEmpty(Model.Poster))
        {
            <img src="@Model.Poster" alt="@Model.Poster" />
        }
        <div class="form-group">
            <input asp-for="FormFile" class="form-control" accept="image/*" />
        </div>
        <div class="form-group">
            <label for="Title">Title</label>
            <input asp-for="Title" class="form-control" placeholder="Enter title" />
        </div>
        <div class="form-group">
            <label for="Producer">Producer</label>
            <input asp-for="Producer" class="form-control" placeholder="Enter producer" />
        </div>
        <div class="form-group">
            <label for="ReleaseYear">Producer</label>
            <input asp-for="ReleaseYear" class="form-control" placeholder="Enter ReleaseYear" />
        </div>
        <div class="form-group">
            <label for="Description">Description</label>
            <textarea asp-for="Description" class="form-control"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Ok</button>
    </form>

Cinema.WebUI/Views/Film/Components/FilmControl/Default.cshtml
@model Cinema.WebUI.Models.FilmControlModel

@if (Model.HasAccess)
{
    <span class="control-content">
        <a href="/Film/EditFilm/@Model.Id">
            <i class="fa fa-pencil" aria-hidden="true"></i>
        </a>
        <a href="/Film/Remove/@Model.Id">
            <i class="fa fa-trash" aria-hidden="true"></i>
        </a>
    </span>
}

Cinema.WebUI/Views/Film/Page.cshtml
@model Cinema.Domain.PaginatedList<Cinema.Domain.FilmModel>

@{

    ViewData["Title"] = "Film Page";
}

@if (!string.IsNullOrEmpty(@ViewBag.MessageError))
{
    <p class="error-message">@ViewBag.MessageError</p>
}
@if (User.Identity.IsAuthenticated)
{
    <a href="/Film/NewFilm" type="button" class="btn btn-success"><i class="fa fa-plus" aria-hidden="true"></i> Add new movie</a>
}

@foreach (var item in Model)
{
    await Html.RenderPartialAsync("_Film.cshtml", item);
}

<nav>
    <ul class="pagination" style="justify-content:center">
        <li class="page-item @(!Model.PreviousPage ? "disabled" : string.Empty)">
            <a class="page-link" href="/Film/Page/@(Model.PageIndex-1)" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>

        @for (int i = Model.FirstItem; i < Model.PageIndex; i++)
        {
            <li class="page-item">
                <a class="page-link" href="/Film/Page/@i">@i</a>
            </li>
        }

        <li class="page-item active"><a class="page-link" href="/Film/Page/@Model.PageIndex">@Model.PageIndex</a></li>

        @for (int i = Model.PageIndex + 1; i <= Model.LastItem; i++)
        {
            <li class="page-item">
                <a class="page-link" href="/Film/Page/@i">@i</a>
            </li>
        }
        <li class="page-item @(!Model.NextPage ? "disabled" : string.Empty)">
            <a class="page-link" href="/Film/Page/@(Model.PageIndex+1)" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
    </ul>
</nav>

Cinema.WebUI/Views/Film/_Film.cshtml
@model Cinema.Domain.FilmModel

<div class="row movie-content">

    @await Component.InvokeAsync("FilmControl", Model)

    <div class="col-md-2 image-content">
        <img src="~/Images/movies/1/mulan.jpg" alt="~/Images/movies/1/mulan.jpg"/>
    </div>
    <div class="col-md-10 information-content">
        <h2>@Model.Title</h2>
        <table>
            <tr>
                <td class="text-right">Release:</td>
                <td>@Model.ReleaseYear</td>
            </tr>
            <tr>
                <td class="text-right">Producer:</td>
                <td>@Model.Producer</td>
            </tr>
            <tr>
                <td class="text-right">Description:</td>
                <td>@Model.Description</td>
            </tr>
        </table>
    </div>
</div>

Cinema.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cinema.WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/movies.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Film" asp-action="Page">Films</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Cinema.WebUI
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>